baseurl = "https://flyhigh-tej.github.io/task--09/"
languageCode = "en-us"
title = "MY EXPERIENCES ON DOING amFOSS TASKS"
author = "Tejasvin V"
canonifyurls = true
paginate = 4
theme = "aether"

[params]
    brand = "Personal Blog"
    description = "aether Hugo theme for blogs"
    

[markup]
  [markup.highlight]
    style = "igor"
